[package]
name = "slope"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"
repository = "https://github.com/SisyphusAeolides/Slope"
description = "Capability-oriented userspace ABI and runtime library for ArachOS"
build = "build.rs"

[features]
default = []
fortran-policy = []

[lib]
path = "src/lib.rs"

[dependencies]
aether = { git = "https://github.com/SisyphusAeolides/Arach-Kernel.git", rev = "6105ab37bf9faebfb03f55101e6cbd3065733052" }
kairos = { git = "https://github.com/SisyphusAeolides/Arach-Kernel.git", rev = "6105ab37bf9faebfb03f55101e6cbd3065733052" }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
